NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('posts/', include('news.urls')),
    path('sign/', include('sign.urls')),
    path('account/', include('allauth.urls')),
    path('appointments/', include('news.urls')),

]

NewsPortal/news/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    PostList, PostDetail, PostCreate, PostSearch, PostUpdate, PostDelete,
    ArticlesPostCreate, ArticlesPostUpdate, ArticlesPostDelete, CategoryListView, subscribe, upgrade_me, logger, index_test,
)


urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('news_create/', PostCreate.as_view(), name='post_create'),
    path('news/<int:pk>/edit/', PostUpdate.as_view(), name='new_edit'),
    path('news/<int:pk>/delete/', PostDelete.as_view()),
    path('articles_create/', ArticlesPostCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', ArticlesPostUpdate.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete/', ArticlesPostDelete.as_view(), name = 'articles_delete'),
    path('upgrade/', upgrade_me, name='upgrade'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('test/', index_test, name='index_test'),
]


NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.http import Http404
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.db.models import signals


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete = models.CASCADE)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating = Sum('rating'))
        pRat = 0
        pRat +=postRat.get('postRating')
        commentRat = self.authorUser.comment_set.aggregate(commentRating = Sum('rating'))
        cRat = 0
        cRat =+commentRat.get('commentRating')
        cRat =+commentRat.get('commentRating')

        self.ratingAuthor = pRat*3+cRat
        self.save()

        def __str__(self):
            return self.authorUser.username


class Category(models.Model):
    name = models.CharField(max_length = 64, unique = True)
    subscribers = models.ManyToManyField(
        User,
        related_name='categories',
    )

    def __str__(self):
        return self.name()

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]
    author = models.ForeignKey(Author, on_delete = models.CASCADE, related_name='author')
    categoryType = models.CharField(max_length = 2, choices = CATEGORY_CHOICES, default = ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add = True)
    postCategory = models.ManyToManyField(Category, through = 'PostCategory')
    title = models.CharField(max_length = 128)
    text = models.TextField()
    rating = models.SmallIntegerField(default = 0)

    def preview(self):
        preview=f'{self.text[:124]}...'
        return preview

    def like(self):
        self.rating +=1
        self.save()

    def dislike(self):
        self.rating -=1
        self.save()

    def __str__(self):
        return f'{self.title} | {self.author}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def get_absolute_url(self):
        return f'posts/{self.id}'

def user_post_save(sender, instance, signal, *args, **kwargs):
    if not instance.is_verified:
        # Send verification email
        send_mail(
            'Verify your QuickPublisher account',
            'Follow this link to verify your account: '
                'http://localhost:8000%s' % reverse('verify', kwargs={'uuid': str(instance.verification_uuid)}),
            'from@quickpublisher.dev',
            [instance.email],
            fail_silently=False,
        )
        signal.post_save.connect(user_post_save, sender=User)


def verify(request, uuid):
    try:
        user = User.objects.get(verification_uuid=uuid, is_verified=False)
    except User.DoesNotExist:
        raise Http404("User does not exist or is already verified")

    user.is_verified = True
    user.save()

    return redirect('news')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete = models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.postThrough.title} | {self.categoryThrough.name}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete = models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete =  models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add = True)
    rating = models.SmallIntegerField(default = 0)

    def like(self):
        self.rating +=1
        self.save()

    def dislike(self):
        self.rating -=1
        self.save()


NewsPortal/news/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = [
           'author',
           'title',
           'text',
           'categoryType',
       ]

       def clean(self):
           cleaned_data = super().clean()
           author = cleaned_data.get("author")
           title = cleaned_data.get("title")
           text = cleaned_data.get("text")
           if title == text:
               raise ValidationError(
                   "Описание не должно быть идентично названию."
               )
           return cleaned_data


class ArticlesPostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = [
           'author',
           'title',
           'text',
           'categoryType',
       ]

       def clean(self):
           cleaned_data = super().clean()
           title = cleaned_data.get("title")
           text = cleaned_data.get("text")
           if title == text:
               raise ValidationError(
                   "Описание не должно быть идентично названию."
               )
           return cleaned_data

class ProfileUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
        ]

NewsPortal/news/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
)
from datetime import datetime
from django.conf import settings
from .models import *
from .filters import PostFilter
from .forms import PostForm

from django.core.mail import EmailMultiAlternatives, send_mail
from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.template.loader import render_to_string

import logging

logger = logging.getLogger('django')


def index_test(request):
    logger.debug("Hello! DEBUG Enjoy")
    logger.info("Hello! INFO Enjoy")
    logger.warning("Hello! WARNING Enjoy")
    logger.error("Hello! ERROR Enjoy")
    logger.critical("Hello! CRITICAL Enjoy")
    return HttpResponse("<p> Сообщение для теста </p>")


def news_home(request):
    news = Post.objects.all()
    return render(request, 'posts.html', {'news': news})


class PostList(ListView):
    model = Post
    ordering = 'title'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 10


class PostSearch(ListView):
    model = Post
    ordering = ['title']
    template_name = 'search.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        context['time_now'] = datetime.utcnow()
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(pk=id)
    is_subscribers = category.subscribers.filter(id=user.id).exists()
    if not is_subscribers:
        category.subscribers.add(user)
        html_content = render_to_string('posts/subscribe.html',
                                        {
                                            'user': user,
                                            'category': category.name,
                                        }
                                        )
        message = EmailMultiAlternatives(
            subject=f'{user} подписка на новости {category.name} оформлена!',
            from_email=settings.EMAIL,
            to=[user.email],
        )
        message.attach_alternative(html_content, 'text/html')
        try:
            message.send()
        except Exception as e:
            print(e)
        finally:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def unsubscribe(request, postCategory):
    user = request.user
    category = Category.objects.get(pk=postCategory)
    is_subscribers = category.subscribers.filter(id=user.id).exists()
    if is_subscribers:
        category.subscribers.delete(user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class PostCreate(CreateView, PermissionRequiredMixin):
    form_class = PostForm
    model = Post
    template_name = 'edit.html'
    permission_required = ('news.add_post')
    contex_object_name = 'create'

    def create_post(request):
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/posts/')

        form = PostForm()
        return render(request, 'news_create.html', {'form': form})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author_post = Author.objects.get(
            author_user=self.request.user
        )
        self.object.save()
        return super().form_valid(form)


class ArticlesPostCreate(CreateView):
    form_class = PostForm
    model = Post
    template_name = 'articles_create.html'

    def create_articles(request):
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/posts/')

        form = PostForm()
        return render(request, 'articles_create.html', {'form': form})

    def form_valid(self, form):
        articles = form.save(commit=False)
        articles.categories = 'AR'
        return super().form_valid(form)


class PostUpdate(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'news_edit.html'
    context_object_name = 'new_edit'


class ArticlesPostUpdate(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'articles_edit.html'
    context_object_name = 'articles_edit'


class PostDelete(DeleteView):
    model = Post
    template_name = 'news_delete.html'
    success_url = reverse_lazy('posts')


class ArticlesPostDelete(DeleteView):
    model = Post
    template_name = 'articles_delete.html'
    success_url = reverse_lazy('posts')


@login_required
def upgrade_me(request):
    user = request.user
    premium_group = User.objects.get(name='author')
    if not request.user.groups.filter(name='author').exists():
        premium_group.user_set.add(user)
    return redirect('/posts/')


class CategoryListView(ListView):
    model = Post
    template_name = 'posts/category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.categoryThrough = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(category=self.categoryThroughy).order_by('-date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.categoryThrough.subscribers.all()
        context['category'] = self.categoryThrough
        return context

NewsPortal/news/templates/add_subscribers.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <title>Document</title>
</head>
<body>
     <h2>
         {{ user }}, Вы подписаны на рассылку новостей в категории "{{ category }}"
     </h2>
     <p>
         После публикации новой статьи или новости в категории "{{ category }}" Вы получите оповещение.
     </p>
     <p>
         С уважением, администрация сайта "News Paper".
     </p>
</body>
</html>

NewsPortal/news/templates/articles_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Добавить статью</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/news/templates/articles_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p> Удаляем "{{ new.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/news/templates/articles_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> Внести исправлениe </h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/news/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}
{% block title %}
Posts
{% endblock title %}

{% block content %}
<h1 class="text-center"> Все новости <span class="text-muted fs-6 fn-normal"> Всего: {{ page_obj.paginator.count}}</span> </h1>
    {% if not is_subscriber %}
        <p class="text-center"> <a href="{% url 'subscribe' category.id%}" class="btn-sm"> Подписаться </a> </p>

{% endif %}
<hr>

<ul class="list-group list-group-flush">

    {%  for post in category_news_list %}
    <li class="list-group-item">
        <small class="fm-bold">{{ post.date | date:'d M Y' }} </small>
        <a href="{% url 'post_detail' post.id %}">{{ post.title }}</a>
        <small class="text-muted">(автор: {{ post.author}})</small> <br>
        <small class="fm-bold"> категории:
            {% for category in post.categoryThrough.all %}
                <a href="{% url 'category_list' category.id %}">{{ category }}</a>
            {% endfor %}
        </small>
        <p> {{new.text|truncatechars:20}}</p>
    </li>
    {% endfor %}
</ul>

<a href=""><li>Контакты</li></a>


{% if not is_subscribe %}
Вы можете подписаться на данную категорию
     {% for category in postCategory %}
         <button><a href="add_subscribe/pk={{category.id}}">{{postCategory}}</a></button>
      {% endfor %}
{% endif %}

    <h2> Новостей нет </h2>

{% if page_obj.has_previous %}

    <a href="?{% url_replace page=1 %}">1</a>
    {% if page_obj.previous_page_number != 1 %}
    <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>

    {% endif %}
{% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}

        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>

        {% endif %}
    {% endif %}

{% endblock content %}

NewsPortal/news/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

NewsPortal/news/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Добавить новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/news/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p> Удаляем "{{ new.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/news/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> Внести исправлениe </h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/news/templates/post.html
{% extends 'flatpages/default.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h1> {{ post.title }}</h1>
<h3>{{ post.dateCreation|date:'d M Y' }}</h3>
<hr>
<p> {{ post.text }} </p>
{% endblock content %}

NewsPortal/news/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h2> Здравствуйте! Новая <a href="{{ link }}"></a> в твоем любимом разделе! </h2>
<p>{{ text }}</p>
</body>
</html>

NewsPortal/news/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}
{% block title %}
Posts
{% endblock title %}

{% block content %}
<h1 class="text-center"> Все новости <span class="text-muted fs-6 fn-normal"> Всего: {{ page_obj.paginator.count}}</span> </h1>
<hr>

<a href=""><li>Контакты</li></a>
{% if posts %}
<div class="table-responsive">
  <table class="table align-middle">

        <tr>

            <td>Статья</td>
            <td>Автор</td>
            <td> Дата </td>
            <td> Текст </td>
            <td> Тип </td>

        </tr>
        {% for new in posts %}
        <tr>

            <td> <a href="{% url 'post_detail' new.id %}">{{ new.title }}</a></td>
            <td><small class="text-muted">(автор: {{ new.author}})</small> <br></td>
            <td><small class="fm-bold">{{new.dateCreation|date:'d M Y' }} </small> </td>
            <td>{{ new.text|truncatechars:20 }} </td>
            <td>{{ new.get_categoryType_display }}{{post.categoryType}}
              {% if not is_subscribe %}
            <b> Подписаться на данную категорию </b>
                 {% for category in post.postCategory.all %}
            <a class="btn" href="add_subscribe/{{ category.id }}">
                <button type="submit" value="follow" name="pk" class="btn btn-light btn-outline-danger">{{ category }}</button>
            </a>

                {% endfor %}
                {% endif %}
            </td>

        </tr>
        {% endfor %}
    </table>
    </div>
{% endif %}


{% if is_subscribe %}
Вы можете отписаться от данной категории
     {% for category in post.postCategory.all %}
         <button><a href="add_subscribe/ pk={{category.id}}">{{category}}</a></button>
      {% endfor %}
{% endif %}

    <h2> Новостей нет </h2>

{% if page_obj.has_previous %}

    <a href="?{% url_replace page=1 %}">1</a>
    {% if page_obj.previous_page_number != 1 %}
    <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>

    {% endif %}
{% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}

        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>

   {% endif %}
{% endif %}

{% endblock content %}

NewsPortal/news/templates/profile_edit.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}
{% block content %}
<h1> Редактировать профиль </h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/news/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
<h1> Поиск новостей </h1>
<hr>

   <form action="" method="get">

       {{ filterset.form.as_p }}


   <input type="submit" value="Найти" />
   </form>


{% if posts %}
    <table>
        <tr>
            <td>Статья</td>
            <td> Дата </td>
            <td> Текст </td>
        </tr>
        {% for new in posts %}
        <tr>
            <td>{{ new.title}}</td>
            <td>{{ new.dateCreation|date:'d M Y' }}</td>
            <td>{{ new.text|truncatechars:20 }} </td>

        </tr>
        {% endfor %}
    </table>

{% else %}
    <h2> Новостей нет </h2>
{% endif %}

   {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}